#!/usr/bin/env bash
# Run every baseline on every (dataset, distribution) combination.
#
# Assumes synth_timestamps artifacts have already been generated by
#   bash scripts/temporal_ann_baselines/run_synth_timestamps.sh
# (i.e. ${artifact_root}/<tag>__<distribution>/ each contains point_timestamps.bin
# + query_ids.bin + range<W>.{query_ranges.bin,gt.ibin}).
#
# Pipeline per (dataset, distribution):
#   1) prepare_sorted_timerange_inputs.py   (idempotent — skip if exists)
#   2) each baseline runner picks the same expanded DATASETS list from
#      datasets.sh and produces ${result_root}/<tag>__<distribution>_<baseline>.tsv
#
# Override which distributions to run via the env var DISTRIBUTIONS_STR.
# Override which baselines to run via env var BASELINES (space-separated).
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${script_dir}/../.." && pwd)"

# Distributions matched by synth_timestamps.py.
: "${DISTRIBUTIONS_STR:=uniform pareto_recent lognormal_recent topic_drift topic_burst topic_seasonal}"
export DISTRIBUTIONS_STR

# Baselines to run. Comment out / remove names to skip.
: "${BASELINES:=dsg serf irangegraph rangefilteredann unify}"

source "${script_dir}/datasets.sh"

mkdir -p "${artifact_root}" "${sorted_root}" "${result_root}" "${log_root}" "${cache_root}"

# ---------------------------------------------------------------------------
# Step 1: ensure sorted inputs exist for every (dataset, distribution).
# ---------------------------------------------------------------------------
echo "[run_all] preparing sorted inputs for ${#DATASETS[@]} combos"
for entry in "${DATASETS[@]}"; do
  IFS='|' read -r tag dataset _type _dist max_points <<< "${entry}"
  [[ -n "${tag}" ]] || continue

  artifacts_dir="${artifact_root}/${tag}"
  sorted_dir="${sorted_root}/${tag}"

  if [[ ! -f "${artifacts_dir}/point_timestamps.bin" ]]; then
    echo "[${tag}] ERROR: artifacts missing at ${artifacts_dir}"
    echo "         run scripts/temporal_ann_baselines/run_synth_timestamps.sh first."
    exit 1
  fi
  if [[ -f "${sorted_dir}/base_sorted.bin" && -f "${sorted_dir}/queries.bin" ]]; then
    echo "[${tag}] sorted inputs exist — skip"
    continue
  fi
  echo "[${tag}] preparing sorted inputs"
  "${python_bin}" "${script_dir}/lib/prepare_sorted_timerange_inputs.py" \
    --dataset "${dataset}" \
    --artifacts-dir "${artifacts_dir}" \
    --output-dir "${sorted_dir}" \
    --max-points "${max_points}"
done

# ---------------------------------------------------------------------------
# Step 2: run each baseline. Each runner iterates DATASETS internally and
# inherits DISTRIBUTIONS_STR (we exported above), so it sees the same 24-entry
# expanded list and emits per-(dataset, distribution) result files.
# ---------------------------------------------------------------------------
declare -A baseline_script=(
  [dsg]="${script_dir}/lib/run_dsg.sh"
  [serf]="${script_dir}/lib/run_serf.sh"
  [irangegraph]="${script_dir}/lib/run_irangegraph.sh"
  [rangefilteredann]="${script_dir}/lib/run_rangefilteredann.sh"
  [unify]="${script_dir}/lib/run_unify.sh"
)

declare -A baseline_probe=(
  [dsg]="${repo_root}/Dynamic-Range-Filtering-ANNS/build/apps/build_static_index"
  [serf]="${repo_root}/SeRF/build/benchmark/serf_annlib"
  [irangegraph]="${repo_root}/iRangeGraph/build/tests/buildindex"
  # rangefilteredann + unify are Python; their wrappers self-check at import time.
)

for name in $BASELINES; do
  runner="${baseline_script[$name]:-}"
  if [[ -z "${runner}" ]]; then
    echo "[run_all] unknown baseline: ${name} (skip)"
    continue
  fi
  probe="${baseline_probe[$name]:-}"
  if [[ -n "${probe}" && ! -x "${probe}" ]]; then
    echo "[run_all] SKIP ${name}: binary not built at ${probe}"
    echo "         build it (see <baseline-dir>/README.md) then re-run."
    continue
  fi
  echo "[run_all] >>> ${name}"
  if "${runner}"; then
    echo "[run_all] <<< ${name} done"
  else
    echo "[run_all] <<< ${name} FAILED (continuing with next baseline)"
  fi
done

echo "[run_all] all baselines complete"
echo "[run_all] results: ${result_root}/<tag>__<distribution>_<baseline>.tsv"
echo "[run_all] logs   : ${log_root}/<tag>__<distribution>/"
